development:
      host: localhost
      adapter: mysql
      database: new
      port: 3306
      username: root
      password: rex220ft

test: &test
      host: localhost
      adapter: mysql
      database: new
      port: 3306
      username: root
      password: rex220ft

production:
      host: localhost
      adapter: mysql
      database: new
      port: 3306
      username: root
      password: rex220ft
cucumber:
  <<: *test
